### ISSUE TITLE
Applying Matrix to later freeTransform-Object

### ISSUE THREAD

**Issue by me-company** [AliasIO/Raphael.FreeTransform#39]
Hi Elbert,

I perform various transformations (scaling, rotating, moving) on Raphael-Objects and want to export that for importing it later.

Afterwards, I save the current matrix of that object. Because I need to remove and add that object again on the paper, but I want it to have the same position, size and rotation as before.

But when I apply the previous Matrix (or transformString) to the new Object (what works excellent, because it has the previous look) AND add freeTransform, it looks like the freeTransform is applied to the original, untransformed object?! It "jumps" back to the original size, scale rotation the second I add freeTransform.

Is it because of the method I add the previous matrix to the object? Doesn't freeTransform look for an existing matrix?

I tried several ways, like matrix.toTransformString (and applying this to Object.transform) or copying the whole transform-Atribute and adding it afterwards.

Please, could you give me a hint, how to fix this?

Thanks in advance and cheers, Christian

**Comment by johnwclark** [comment]
I am also having a similar.  I have a text element that I moved with a freeTransform, which later gets unplugged, and when I later go to put a freeTransform on it, the handles don't respect the current transform, and are showing in the original position.

Is there a simple way to go apply a transform string onto the freeTransform object.  It seems like they use a completely different representation for the transform data.
