### ISSUE TITLE
How to constrain elements so they cannot be dragged past the dimensions of the paper

### ISSUE THREAD

**Issue by distracteddev** [AliasIO/Raphael.FreeTransform#98]
Currently the 'boundary' option only stop the element's handles from leaving the paper, however I would like it to behave such that any part of the element I am dragging will not be able to be dragged outside the dimensions of the paper.

Thanks again!

**Comment by eduardodallmann** [comment]
me too

> I would like it to behave such that any part of the element I am dragging will not be able to be dragged outside the dimensions of the paper
